# Generated by Django 2.2.14 on 2020-09-10 10:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitute', models.FloatField()),
                ('delivery_min_price', models.IntegerField(default=400)),
                ('wallpaper', models.ImageField(blank=True, null=True, upload_to='place_wallpapers/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('delivery_address', django.contrib.postgres.fields.jsonb.JSONField()),
                ('delivery_price', models.IntegerField(default=0)),
                ('contact_phone', models.CharField(default='', max_length=20)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.Place')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_item_image/')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.Place')),
            ],
        ),
    ]
