# Generated by Django 2.2.14 on 2020-08-04 11:07

from django.db import migrations, models
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to=user_app.models.get_image_path),
        ),
    ]
