# Generated by Django 2.2.14 on 2020-08-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200804_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='place_wallpapers/'),
        ),
    ]
