# Generated by Django 3.1.1 on 2020-09-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200924_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
