# Generated by Django 2.2.14 on 2020-08-22 08:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('delivery_address', django.contrib.postgres.fields.jsonb.JSONField()),
                ('delivery_price', models.IntegerField(default=0)),
                ('contact_phone', models.CharField(default='', max_length=20)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.Place')),
            ],
        ),
    ]
