# Generated by Django 3.1.1 on 2020-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('COURIER', 'COURIER'), ('BUSINESS', 'BUSINESS')], max_length=20),
        ),
    ]
