# Generated by Django 2.2.14 on 2020-08-22 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20200822_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 22)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.time(20, 57, 46, 982190)),
        ),
    ]
