# Generated by Django 2.2.14 on 2020-08-22 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20200822_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.time(17, 45, 43, 501378)),
        ),
    ]
