# Generated by Django 3.1.1 on 2020-09-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_auto_20200929_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('COURIER', 'COURIER'), ('USER', 'USER'), ('BUSINESS', 'BUSINESS')], default='USER', max_length=20),
        ),
    ]
