# Generated by Django 2.2.14 on 2020-08-22 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_auto_20200822_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 22, 17, 47, 37, 703674, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.time(17, 47, 37, 703707)),
        ),
    ]
