# Generated by Django 2.2.14 on 2020-08-22 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_auto_20200822_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.time(23, 58, 45, 637173)),
        ),
    ]
