# Generated by Django 3.1.1 on 2020-11-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_order_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
