# Generated by Django 3.1.1 on 2020-11-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_auto_20201102_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('user_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
    ]
