# Generated by Django 2.2.14 on 2020-08-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_auto_20200823_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
