# Generated by Django 3.1.1 on 2020-11-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_pushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='place_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='user_id',
            field=models.CharField(default='default', max_length=1000),
        ),
    ]
