# Generated by Django 3.1.1 on 2020-11-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_auto_20201109_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='place_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
