# Generated by Django 3.1.1 on 2020-11-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_auto_20201109_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
