# Generated by Django 3.1.1 on 2020-11-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
