# Generated by Django 3.1.1 on 2020-11-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='place_id',
            new_name='place',
        ),
    ]
