# Generated by Django 3.1.1 on 2020-11-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_auto_20201123_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='place_id',
        ),
    ]
