# Generated by Django 3.1.1 on 2020-11-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0026_auto_20201127_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='not_working',
            field=models.BooleanField(default=False, verbose_name='Не работает'),
        ),
    ]
