# Generated by Django 3.1.1 on 2020-12-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_auto_20201128_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
