# Generated by Django 3.1.1 on 2020-12-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0029_order_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stopped',
            field=models.BooleanField(default=False),
        ),
    ]
