# Generated by Django 3.1.1 on 2020-12-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0030_menuitem_stopped'),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexMapGeocoderKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000)),
            ],
        ),
    ]
