# Generated by Django 3.1.1 on 2021-01-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0033_order_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_app.user')),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
    ]
