# Generated by Django 3.1.1 on 2021-02-22 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0034_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.menuitemcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_item_image/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.place', verbose_name='Приявязанное заведение'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='stopped',
            field=models.BooleanField(default=False, verbose_name='Приостановлено'),
        ),
        migrations.AlterField(
            model_name='menuitemcategory',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.JSONField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Сумма доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.JSONField(default={}, verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.place', verbose_name='Индекс заведения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время заказа'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='categories',
            field=models.JSONField(blank=True, null=True, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='place',
            name='delivery_min_price',
            field=models.IntegerField(default=400, verbose_name='Минимальная сумма доставки'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='place',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='place_wallpapers/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.JSONField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.place', verbose_name='Связанное заведение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('COURIER', 'COURIER'), ('USER', 'USER'), ('BUSINESS', 'BUSINESS')], default='USER', max_length=20, verbose_name='Роль'),
        ),
    ]
