# Generated by Django 3.1.1 on 2021-02-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0035_auto_20210222_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocodeType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sale', models.IntegerField(blank=True, default=0)),
                ('bonus', models.IntegerField(blank=True, default=0)),
                ('place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.place')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.promocodetype')),
            ],
        ),
    ]
