# Generated by Django 3.1.1 on 2021-02-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0036_promocode_promocodetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='bonus',
            field=models.IntegerField(blank=True, default=0, verbose_name='Бонус тг'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.place', verbose_name='Заведение'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='sale',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка %'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.promocodetype', verbose_name='Тип'),
        ),
    ]
