# Generated by Django 3.1.1 on 2021-02-23 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0037_auto_20210222_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_multiple',
            field=models.BooleanField(default=False, verbose_name='Многоразовый'),
        ),
        migrations.CreateModel(
            name='UsedPromocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
