# Generated by Django 3.1.1 on 2021-02-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0038_auto_20210223_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodetype',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
