# Generated by Django 3.1.1 on 2021-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0039_promocodetype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promoCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
