# Generated by Django 3.1.1 on 2021-02-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0040_order_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderTotal',
            field=models.IntegerField(default=0, verbose_name='Общая сумма'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderTotalWithSale',
            field=models.IntegerField(default=0, verbose_name='Сумма со скидкой'),
        ),
    ]
