# Generated by Django 3.1.1 on 2021-02-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0041_auto_20210225_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderTotal',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderTotalWithSale',
            new_name='total_with_promoCode',
        ),
    ]
