# Generated by Django 3.1.1 on 2021-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0043_deliverydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_with_promoCode',
            field=models.IntegerField(default=0, null=True, verbose_name='Сумма со скидкой'),
        ),
    ]
