# Generated by Django 3.1.1 on 2021-04-02 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0044_auto_20210226_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='related_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунта заведения для заказа'),
        ),
    ]
