# Generated by Django 3.1.1 on 2021-04-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0045_place_related_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='related_user',
            new_name='user_to_order',
        ),
    ]
